package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'RunTestsDefaultDockerWrapper'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("RunTestsDefaultDockerWrapper")) {
    expectSteps {
        maven {
            goals = "clean test"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
            dockerImage = "maven:3-ibmjava-8-alpine"
            dockerImagePlatform = MavenBuildStep.ImagePlatform.Linux
            param("maven.path", "%teamcity.tool.maven.DEFAULT%")
        }
    }
    steps {
        update<MavenBuildStep>(0) {
            localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
            param("teamcity.tool.jacoco", "")
        }
    }
}
