package patches.templates

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2018_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the template with id = 'RunTestsUseOwnDockerWrapperTemplate'
accordingly, and delete the patch script.
*/
changeTemplate(RelativeId("RunTestsUseOwnDockerWrapperTemplate")) {
    expectSteps {
        maven {
            id = "RUNNER_1"
            goals = "clean test"
            runnerArgs = "-Dmaven.test.failure.ignore=true"
            dockerImage = "maven:3-ibmjava-8-alpine"
            dockerImagePlatform = MavenBuildStep.ImagePlatform.Linux
            param("localRepoScope", "BUILD_CONFIGURATION")
            param("maven.path", "%teamcity.tool.maven.DEFAULT%")
        }
    }
    steps {
        update<MavenBuildStep>(0) {
            id = "RUNNER_1"
            localRepoScope = MavenBuildStep.RepositoryScope.BUILD_CONFIGURATION
            param("teamcity.tool.jacoco", "")
        }
    }
}
